using System.Text.Json.Serialization;
using Platega.Serialization;

namespace Platega.Payments;

/// <summary>
/// Parameters of a new payment. When <see cref="Method"/> is <c>null</c> the payer chooses the method on the
/// Platega payment page (<c>POST /v2/transaction/process</c>); otherwise the method is fixed
/// (<c>POST /transaction/process</c>). The transaction id is always generated by Platega.
/// </summary>
public sealed record CreatePaymentRequest
{
    /// <summary>Amount and currency, e.g. <c>new Money(500, "RUB")</c>.</summary>
    public required Money Amount { get; init; }

    /// <summary>Description shown to the payer.</summary>
    public required string Description { get; init; }

    /// <summary>Where the payer is redirected after a successful payment.</summary>
    public required Uri ReturnUrl { get; init; }

    /// <summary>Where the payer is redirected after a failed payment.</summary>
    public required Uri FailedUrl { get; init; }

    /// <summary>Fixed payment method, or <c>null</c> to let the payer choose.</summary>
    public PaymentMethod? Method { get; init; }

    /// <summary>Free-form data returned in the status response and in callbacks.</summary>
    public string? Payload { get; init; }

    /// <summary>Your internal order id.</summary>
    public string? OrderId { get; init; }

    /// <summary>Payer data for the anti-fraud system. Mandatory for some merchant categories.</summary>
    public PayerMetadata? Metadata { get; init; }
}

/// <summary>Payer data for the anti-fraud system (<c>metadata</c>).</summary>
public sealed record PayerMetadata
{
    /// <summary>Unique payer id in your system, e.g. a Telegram user id.</summary>
    public required string UserId { get; init; }

    /// <summary>Any additional payer data, e.g. a username.</summary>
    public required string UserName { get; init; }

    /// <summary>Payer IP address.</summary>
    public string? ClientIp { get; init; }
}

/// <summary>Result of payment creation, normalized across both creation endpoints.</summary>
public sealed record CreatedPayment
{
    /// <summary>Platega transaction id; use it to query the status.</summary>
    public required Guid TransactionId { get; init; }

    /// <summary>Status right after creation, normally <see cref="PaymentStatus.Pending"/>.</summary>
    public required PaymentStatus Status { get; init; }

    /// <summary>Payment page the payer must be sent to.</summary>
    public required string PaymentUrl { get; init; }

    /// <summary>Time left until the payment link expires.</summary>
    public TimeSpan? ExpiresIn { get; init; }

    /// <summary>USDT exchange rate applied to the transaction.</summary>
    public decimal? UsdtRate { get; init; }

    /// <summary>Human-readable method name, e.g. <c>SBPQR</c>. Present only for a fixed method.</summary>
    public string? PaymentMethodName { get; init; }

    /// <summary>Amount echoed by the API. Present only for a fixed method.</summary>
    public Money? Amount { get; init; }

    /// <summary>Merchant id echoed by the API. Present only for a fixed method.</summary>
    public string? MerchantId { get; init; }
}

/// <summary>Transaction details returned by <c>GET /transaction/{id}</c>.</summary>
public sealed record PlategaTransaction
{
    /// <summary>Transaction id.</summary>
    public required Guid Id { get; init; }

    /// <summary>Current transaction status.</summary>
    public PaymentStatus Status { get; init; }

    /// <summary>Order amount and currency (<c>paymentDetails</c>).</summary>
    [JsonPropertyName("paymentDetails")]
    [JsonConverter(typeof(FlexibleMoneyConverter))]
    public Money? Amount { get; init; }

    /// <summary>Merchant display name.</summary>
    public string? MerchantName { get; init; }

    /// <summary>Merchant id. The API spells the field <c>mechantId</c>.</summary>
    [JsonPropertyName("mechantId")]
    public string? MerchantId { get; init; }

    /// <summary>Commission in the payment currency.</summary>
    [JsonPropertyName("comission")]
    public decimal? Commission { get; init; }

    /// <summary>Commission converted to USDT.</summary>
    [JsonPropertyName("comissionUsdt")]
    public decimal? CommissionUsdt { get; init; }

    /// <summary>Commission type code as returned by Platega.</summary>
    [JsonPropertyName("comissionType")]
    public int? CommissionType { get; init; }

    /// <summary>Amount converted to USDT.</summary>
    public decimal? AmountUsdt { get; init; }

    /// <summary>Human-readable method name, e.g. <c>SBPQR</c>.</summary>
    public string? PaymentMethod { get; init; }

    /// <summary>Time left until the payment link expires.</summary>
    [JsonConverter(typeof(TolerantTimeSpanConverter))]
    public TimeSpan? ExpiresIn { get; init; }

    /// <summary>Redirect address after a successful payment (<c>return</c>).</summary>
    [JsonPropertyName("return")]
    public string? ReturnUrl { get; init; }

    /// <summary>QR payload or payment link; <c>null</c> until a method is chosen.</summary>
    public string? Qr { get; init; }

    /// <summary>Platega success page for this transaction.</summary>
    public string? PayformSuccessUrl { get; init; }

    /// <summary>The <c>payload</c> passed at creation.</summary>
    public string? Payload { get; init; }

    /// <summary>External id; the <c>orderId</c> from the request is not echoed here.</summary>
    public string? ExternalId { get; init; }

    /// <summary>Description shown to the payer.</summary>
    public string? Description { get; init; }

    /// <summary>Refund state; not in the documentation, returned by the live API (<c>null</c> when there is no refund).</summary>
    public string? RefundStatus { get; init; }

    /// <summary>Refund state explanation; not in the documentation, returned by the live API.</summary>
    public string? RefundStatusMessage { get; init; }

    /// <summary>Creation time; not in the documentation, returned by the live API.</summary>
    public DateTimeOffset? CreatedAt { get; init; }
}

/// <summary>Host-to-host payment data returned by <c>GET /h2h/{id}</c>.</summary>
public sealed record H2HPaymentData
{
    /// <summary>Amount to pay.</summary>
    public decimal Amount { get; init; }

    /// <summary>QR payload or payment link, e.g. an <c>https://qr.nspk.ru/...</c> URL.</summary>
    public required string Qr { get; init; }
}

/// <summary>File format of a transaction export.</summary>
public enum TransactionExportFormat
{
    /// <summary>CSV file.</summary>
    Csv,
    /// <summary>Excel file.</summary>
    Excel,
    /// <summary>JSON file.</summary>
    Json,
}

/// <summary>Filters of a transaction export.</summary>
public sealed record TransactionExportRequest
{
    /// <summary>Start of the period (inclusive).</summary>
    public required DateTimeOffset From { get; init; }

    /// <summary>End of the period (inclusive).</summary>
    public required DateTimeOffset To { get; init; }

    /// <summary>
    /// Statuses to include; an empty list means all statuses. Sent as the numeric codes the export endpoint expects:
    /// 1 Pending, 6 Canceled, 7 Confirmed, 9 Chargebacked.
    /// </summary>
    public IReadOnlyList<PaymentStatus> Statuses { get; init; } = [];

    /// <summary>Payment methods to include; an empty list means all methods.</summary>
    public IReadOnlyList<PaymentMethod> PaymentMethods { get; init; } = [];

    /// <summary>Time zone used to render dates in the file.</summary>
    public string TimeZoneId { get; init; } = "UTC";
}
